### ISSUE TITLE
NEO4J Hetionet explorer is not working

### ISSUE THREAD

**Issue by tsarfaty-lab** [hetio/hetionet#38]
Hi everyone,

I tried connecting to the NEO4J browser with hetionet from the het.io website (https://neo4j.het.io/browser/) but it seems to be down or not working. Does anyone know any workaround for this? Has the web address changed? The error reads 'The site cannot be reached'. I've tried connecting on different computers, and on different browsers too. 

Thank you in advance!

**Comment by dhimmel** [comment]
Okay, I SSHed into the instance `ssh ubuntu@neo4j.het.io` and rebooted. Database is back up.

But first I looked at the logs via `tail neo4j-logs/debug.log`. Pasting them here in case this helps us diagnose what happened

```
2021-06-17 03:09:32.931+0000 WARN [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline, remote peer unexpectedly closed connection: [id: 0xed020bfe, L:/172.17.0.2:7687 - R:/24.163.62.80:61045]
2021-06-17 03:17:33.901+0000 WARN [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline, remote peer unexpectedly closed connection: [id: 0x7eff7f18, L:/172.17.0.2:7687 - R:/24.163.62.80:58426]
2021-06-17 03:26:09.206+0000 ERROR [o.n.b.t.p.HouseKeeper] Fatal error occurred when handling a client connection: [id: 0x1339a49e, L:/172.17.0.2:7687 - R:/24.163.62.80:61048] readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2021-06-17 03:27:39.319+0000 ERROR [o.n.b.t.TransportSelectionHandler] Fatal error occurred when initialising pipeline: [id: 0x087aa31f, L:/172.17.0.2:7687 - R:/24.163.62.80:58436] readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2021-06-17 03:45:16.086+0000 ERROR [o.n.b.t.p.HouseKeeper] Fatal error occurred when handling a client connection: [id: 0x7dd26d7a, L:/172.17.0.2:7687 - R:/24.163.62.80:61353] readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2021-06-17 04:03:46.102+0000 ERROR [o.n.b.t.p.HouseKeeper] Fatal error occurred when handling a client connection: [id: 0x2fa16a63, L:/172.17.0.2:7687 - R:/24.163.62.80:61350] readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
```

CC @dongbohu in case these logs mean anything to you!

**Comment by tsarfaty-lab** [comment]
It seems to be working again! Not sure what happened for the server to not work. Nevertheless, thank you!

**Comment by dhimmel** [comment]
> Not sure what happened for the server to not work.

I restarted it!

**Comment by dhimmel** [comment]
Closing since we now have uptime alerts, see https://github.com/hetio/hetionet/issues/45.
